[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]

solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200

fs_permissions = [
  { access = "read", path = "./" }
]

[rpc_endpoints]
arc_testnet = "https://rpc.testnet.arc.network"

[etherscan]
arc_testnet = { key = "DUMMY" }

[dependencies]
forge-std = { git = "https://github.com/foundry-rs/forge-std.git", branch = "master" }

