name: mint arc

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mint:
    runs-on: ubuntu-latest

    env:
      ARC_TESTNET_RPC_URL: ${{ secrets.ARC_TESTNET_RPC_URL }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      TOKEN: '0x0E25953ff35379c3C4b18Af7bbEAF8734EA86985'
      TO: '0x9F5D4A3a8aBC0E4E76b60b91cd769f9cFE69Dcf4'
      AMOUNT: '900000000000000000000000'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Verify Foundry
        run: |
          forge --version
          cast --version

      

      - name: Mint ARC tokens
        run: |
          cast send $TOKEN \
            "mintTo(address,uint256)" \
            $TO $AMOUNT \
            --rpc-url $ARC_TESTNET_RPC_URL \
            --private-key $PRIVATE_KEY
