name: whisper Agent

permissions:
  contents: read
  actions: write

on:
  workflow_dispatch:
    inputs:
      question:
        description: "audio to transcribe"
        required: true
        type: string

      emails:
        description: "email to send audio to"
        required: true
        type: string

     

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install ctransformers gdown yagmail

      - name: Cache whisper large model
        id: cache-model
        uses: actions/cache@v3
        with:
          path: model
          key: whisper-large

      - name: Download whisper large
        if: steps.cache-model.outputs.cache-hit != 'true'
        run: |
          mkdir -p model
          gdown --id 1tDKohelhAiA6hSXIqm9inqKGNDxeaWf8 -O model/whisper large

      - name: Verify model
        run: |
          ls -lh model
          file model/whisperlarge

      - name: Run agent
        run: |
          python whisper.py \
            "${{ github.event.inputs.question }}" \
            '${{ github.event.inputs.emails }}' \
            

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: result-${{ github.run_id }}
          path: result.json
